name: Laravel CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1

    - name: Install dependencies
      run: composer install --prefer-dist --no-interaction

    - name: Generate application key
      run: php artisan key:generate

    - name: Set up .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Set up database
      run: |
        php artisan config:cache
        php artisan migrate --force
      env:
        DB_CONNECTION: mysql
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: 3306
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    - name: Run tests
      run: php artisan test
      env:
        DB_CONNECTION: mysql
        DB_HOST: 103.247.10.164
        DB_PORT: 3306
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

  deploy:
    runs-on: ubuntu-latest
    needs: install
    steps:
    - uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1

    - name: Install dependencies
      run: composer install --prefer-dist --no-interaction

    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
        rsync -avz -e "ssh -i private_key -o StrictHostKeyChecking=no" ./ ${SSH_USERNAME}@${SSH_HOST}:/var/www/laravel/cicd/testing-php8-1
        ssh -i private_key -o StrictHostKeyChecking=no ${SSH_USERNAME}@${SSH_HOST} "cd /var/www/laravel/cicd/testing-php8-1 && php artisan migrate --force"
